version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - cd frontend
      - npm install
      - cd ../backend
      - npm install

  pre_build:
    commands:
      - cd frontend
      - npm run build
      - aws s3 sync build/ s3://srirammirchibandi-assets-dev/ --delete

  build:
    commands:
      - cd ../backend
      - npm run test

artifacts:
  files:
    - '**/*'
  base-directory: backend
  name: backend-$(date +%Y-%m-%d-%H-%M-%S)

cache:
  paths:
    - '/root/.npm/**/*'
    - 'frontend/node_modules/**/*'
    - 'backend/node_modules/**/*' 